remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Research Agent Mobile
description: A Mobile-First Agentic Interface for Monitoring and Steering Machine Learning Experiments
